/// World countries mapped to their ISO 4217 currency codes.
///
/// Used by system settings to populate country/currency dropdowns
/// and auto-select currency when a country is chosen.

const Map<String, String> countryCurrencyMap = {
  // A
  'Afghanistan': 'AFN',
  'Albania': 'ALL',
  'Algeria': 'DZD',
  'Andorra': 'EUR',
  'Angola': 'AOA',
  'Antigua and Barbuda': 'XCD',
  'Argentina': 'ARS',
  'Armenia': 'AMD',
  'Australia': 'AUD',
  'Austria': 'EUR',
  'Azerbaijan': 'AZN',
  // B
  'Bahamas': 'BSD',
  'Bahrain': 'BHD',
  'Bangladesh': 'BDT',
  'Barbados': 'BBD',
  'Belarus': 'BYN',
  'Belgium': 'EUR',
  'Belize': 'BZD',
  'Benin': 'XOF',
  'Bhutan': 'BTN',
  'Bolivia': 'BOB',
  'Bosnia and Herzegovina': 'BAM',
  'Botswana': 'BWP',
  'Brazil': 'BRL',
  'Brunei': 'BND',
  'Bulgaria': 'BGN',
  'Burkina Faso': 'XOF',
  'Burundi': 'BIF',
  // C
  'Cabo Verde': 'CVE',
  'Cambodia': 'KHR',
  'Cameroon': 'XAF',
  'Canada': 'CAD',
  'Central African Republic': 'XAF',
  'Chad': 'XAF',
  'Chile': 'CLP',
  'China': 'CNY',
  'Colombia': 'COP',
  'Comoros': 'KMF',
  'Congo (DRC)': 'CDF',
  'Congo (Republic)': 'XAF',
  'Costa Rica': 'CRC',
  'Croatia': 'EUR',
  'Cuba': 'CUP',
  'Cyprus': 'EUR',
  'Czech Republic': 'CZK',
  // D
  'Denmark': 'DKK',
  'Djibouti': 'DJF',
  'Dominica': 'XCD',
  'Dominican Republic': 'DOP',
  // E
  'East Timor': 'USD',
  'Ecuador': 'USD',
  'Egypt': 'EGP',
  'El Salvador': 'USD',
  'Equatorial Guinea': 'XAF',
  'Eritrea': 'ERN',
  'Estonia': 'EUR',
  'Eswatini': 'SZL',
  'Ethiopia': 'ETB',
  // F
  'Fiji': 'FJD',
  'Finland': 'EUR',
  'France': 'EUR',
  // G
  'Gabon': 'XAF',
  'Gambia': 'GMD',
  'Georgia': 'GEL',
  'Germany': 'EUR',
  'Ghana': 'GHS',
  'Greece': 'EUR',
  'Grenada': 'XCD',
  'Guatemala': 'GTQ',
  'Guinea': 'GNF',
  'Guinea-Bissau': 'XOF',
  'Guyana': 'GYD',
  // H
  'Haiti': 'HTG',
  'Honduras': 'HNL',
  'Hungary': 'HUF',
  // I
  'Iceland': 'ISK',
  'India': 'INR',
  'Indonesia': 'IDR',
  'Iran': 'IRR',
  'Iraq': 'IQD',
  'Ireland': 'EUR',
  'Israel': 'ILS',
  'Italy': 'EUR',
  'Ivory Coast': 'XOF',
  // J
  'Jamaica': 'JMD',
  'Japan': 'JPY',
  'Jordan': 'JOD',
  // K
  'Kazakhstan': 'KZT',
  'Kenya': 'KES',
  'Kiribati': 'AUD',
  'Kosovo': 'EUR',
  'Kuwait': 'KWD',
  'Kyrgyzstan': 'KGS',
  // L
  'Laos': 'LAK',
  'Latvia': 'EUR',
  'Lebanon': 'LBP',
  'Lesotho': 'LSL',
  'Liberia': 'LRD',
  'Libya': 'LYD',
  'Liechtenstein': 'CHF',
  'Lithuania': 'EUR',
  'Luxembourg': 'EUR',
  // M
  'Madagascar': 'MGA',
  'Malawi': 'MWK',
  'Malaysia': 'MYR',
  'Maldives': 'MVR',
  'Mali': 'XOF',
  'Malta': 'EUR',
  'Marshall Islands': 'USD',
  'Mauritania': 'MRU',
  'Mauritius': 'MUR',
  'Mexico': 'MXN',
  'Micronesia': 'USD',
  'Moldova': 'MDL',
  'Monaco': 'EUR',
  'Mongolia': 'MNT',
  'Montenegro': 'EUR',
  'Morocco': 'MAD',
  'Mozambique': 'MZN',
  'Myanmar': 'MMK',
  // N
  'Namibia': 'NAD',
  'Nauru': 'AUD',
  'Nepal': 'NPR',
  'Netherlands': 'EUR',
  'New Zealand': 'NZD',
  'Nicaragua': 'NIO',
  'Niger': 'XOF',
  'Nigeria': 'NGN',
  'North Korea': 'KPW',
  'North Macedonia': 'MKD',
  'Norway': 'NOK',
  // O
  'Oman': 'OMR',
  // P
  'Pakistan': 'PKR',
  'Palau': 'USD',
  'Palestine': 'ILS',
  'Panama': 'PAB',
  'Papua New Guinea': 'PGK',
  'Paraguay': 'PYG',
  'Peru': 'PEN',
  'Philippines': 'PHP',
  'Poland': 'PLN',
  'Portugal': 'EUR',
  // Q
  'Qatar': 'QAR',
  // R
  'Romania': 'RON',
  'Russia': 'RUB',
  'Rwanda': 'RWF',
  // S
  'Saint Kitts and Nevis': 'XCD',
  'Saint Lucia': 'XCD',
  'Saint Vincent and the Grenadines': 'XCD',
  'Samoa': 'WST',
  'San Marino': 'EUR',
  'Sao Tome and Principe': 'STN',
  'Saudi Arabia': 'SAR',
  'Senegal': 'XOF',
  'Serbia': 'RSD',
  'Seychelles': 'SCR',
  'Sierra Leone': 'SLE',
  'Singapore': 'SGD',
  'Slovakia': 'EUR',
  'Slovenia': 'EUR',
  'Solomon Islands': 'SBD',
  'Somalia': 'SOS',
  'South Africa': 'ZAR',
  'South Korea': 'KRW',
  'South Sudan': 'SSP',
  'Spain': 'EUR',
  'Sri Lanka': 'LKR',
  'Sudan': 'SDG',
  'Suriname': 'SRD',
  'Sweden': 'SEK',
  'Switzerland': 'CHF',
  'Syria': 'SYP',
  // T
  'Taiwan': 'TWD',
  'Tajikistan': 'TJS',
  'Tanzania': 'TZS',
  'Thailand': 'THB',
  'Togo': 'XOF',
  'Tonga': 'TOP',
  'Trinidad and Tobago': 'TTD',
  'Tunisia': 'TND',
  'Turkey': 'TRY',
  'Turkmenistan': 'TMT',
  'Tuvalu': 'AUD',
  // U
  'Uganda': 'UGX',
  'Ukraine': 'UAH',
  'United Arab Emirates': 'AED',
  'United Kingdom': 'GBP',
  'United States': 'USD',
  'Uruguay': 'UYU',
  'Uzbekistan': 'UZS',
  // V
  'Vanuatu': 'VUV',
  'Vatican City': 'EUR',
  'Venezuela': 'VES',
  'Vietnam': 'VND',
  // Y
  'Yemen': 'YER',
  // Z
  'Zambia': 'ZMW',
  'Zimbabwe': 'ZWL',
};

/// Sorted list of all country names.
List<String> get allCountries {
  final countries = countryCurrencyMap.keys.toList()..sort();
  return countries;
}

/// Sorted list of unique currency codes.
List<String> get allCurrencies {
  final currencies = countryCurrencyMap.values.toSet().toList()..sort();
  return currencies;
}
